# Generated by Django 5.2.5 on 2025-09-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_security.ip_tracking', '0003_requestlog_city_requestlog_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='path',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
